---
kind: Service
apiVersion: v1
metadata:
  namespace: test
  name: svc-rocketmq-broker-master
  labels:
    app: rocketmq-broker
spec:
  ports:
  - name: rocketmq-port-10909
    protocol: TCP
    port: 10909
    targetPort: 10909
  - name: rocketmq-port-10911
    protocol: TCP
    port: 10911
    targetPort: 10911
  selector:
    app: rocketmq-broker-master
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: test
  name: rocketmq-broker-master
  labels:
    app: rocketmq-broker-master
spec:
  replicas: 1
  serviceName: svc-rocketmq-broker-master
  selector:
    matchLabels:
      app: rocketmq-broker-master
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-broker-master
    spec:
      containers:
      - image: reg.maihaoche.com/library/rocketmq-broker:4.7.0
        name: rocketmq-broker-master
        imagePullPolicy: Always
        env:
          - name: JAVA_OPT
            value: "-Duser.home=/opt -Xms2g -Xmx2g"
          - name: BROKER_CLUSTER_NAME
            value: "camaro"
          - name: BROKER_ID
            value: "0"
          - name: BROKER_ROLE
            value: "ASYNC_MASTER"
          - name: NAME_SRV_ADDR
            value: "rocketmq-namesrv-0.namesrv.middle:9876;rocketmq-namesrv-1.namesrv.middle:9876"
          - name: AUTO_CREATE_TOPIC_ENABLE
            value: "FALSE"
        ports:
        - protocol: TCP
          containerPort: 10909
        - protocol: TCP
          containerPort: 10911
        resources:
          requests:
            cpu: 500m
            memory: 3Gi
          limits:
            cpu: 2
            memory: 3Gi
        volumeMounts:
        - name: mqstore
          mountPath: /opt/store
        - name: mqlogs
          mountPath: /opt/logs
        readinessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 120
          periodSeconds: 10
      imagePullSecrets:
        - name: reg-out
  volumeClaimTemplates:
    - metadata:
        name: mqstore
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Gi"
        storageClassName: managed-nfs-storage-02
    - metadata:
        name: mqlogs
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Gi"
        storageClassName: managed-nfs-storage
