---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: middle
  name: cm-rocketmq-broker-master
data:
  broker.conf: |
    brokerClusterName=camaro
    brokerId=0
    brokerName=broker-0/1
    brokerRole=ASYNC_MASTER
    namesrvAddr=rocketmq-namesrv-0.namesrv.middle:9876;rocketmq-namesrv-1.namesrv.middle:9876
    waitTimeMillsInSendQueue=5000
    deleddWhen=04
    fileReservedTime=720
    flushDiskType=ASYNC_FLUSH
    autoCreateTopicEnable=FALSE
    diskMaxUsedSpaceRatio=88
# brokerName一致brokerId不一样为一个主从（brokerRole=ASYNC_MASTER，brokerRole=SLAVE）

---
kind: Service
apiVersion: v1
metadata:
  namespace: middle
  name: svc-rocketmq-broker-master
  labels:
    app: rocketmq-broker
spec:
  ports:
  - name: rocketmq-port-10909
    protocol: TCP
    port: 10909
    targetPort: 10909
  - name: rocketmq-port-10911
    protocol: TCP
    port: 10911
    targetPort: 10911
  selector:
    app: rocketmq-broker-master
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: middle
  name: rocketmq-broker-master
  labels:
    app: rocketmq-broker-master
spec:
  replicas: 2
  serviceName: svc-rocketmq-broker-master
  selector:
    matchLabels:
      app: rocketmq-broker-master
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-broker-master
    spec:
      containers:
      - image: reg.maihaoche.com/library/rocketmq-broker:4.2.0
        name: rocketmq-broker-master
        env:
          - name: JAVA_OPT
            value: "-Duser.home=/opt -Xms2g -Xmx2g"
        ports:
        - protocol: TCP
          containerPort: 10909
        - protocol: TCP
          containerPort: 10911
        resources:
          requests:
            cpu: 500m
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: mqstore
          mountPath: /opt/store
        - name: conf
          mountPath: /opt/rocketmq-4.2.0/conf/broker.conf
          subPath: broker.conf
        readinessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 120
          periodSeconds: 10
      imagePullSecrets:
        - name: reg-out
      volumes:
        - name: conf
          configMap:
            name: cm-rocketmq-broker-master
  volumeClaimTemplates:
    - metadata:
        name: mqstore
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "20Gi"
        storageClassName: alicloud-disk-ssd-hangzhou-be
