---
kind: Service
apiVersion: v1
metadata:
  namespace: NAMESPACE
  name: svc-rocketmq
  labels:
    app: rocketmq-namesrv
spec:
  ports:
  - protocol: TCP
    port: 9876
    targetPort: 9876
  selector:
    app: rocketmq-namesrv
  type: ClusterIP
  sessionAffinity: ClientIP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: NAMESPACE
  name: rocketmq-namesrv
  labels:
    app: rocketmq-namesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-namesrv
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
    spec:
      containers:
      - image: reg.haimaiche.net/library/rocketmq-namesrv:4.7.1
        imagePullPolicy: Always
        name: rocketmq-namesrv
        env:
        - name: JAVA_OPT
          value: "-Duser.home=/opt -Xms1g -Xmx1g"
        ports:
        - protocol: TCP
          containerPort: 9876
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 120
          periodSeconds: 10
      imagePullSecrets:
        - name: reg-in