---
kind: Service
apiVersion: v1
metadata:
  namespace: test
  name: namesrv
  labels:
    app: rocketmq-namesrv
spec:
  ports:
  - protocol: TCP
    port: 9876
    targetPort: 9876
  selector:
    app: rocketmq-namesrv
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: test
  name: rocketmq-namesrv
  labels:
    app: rocketmq-namesrv
spec:
  replicas: 1
  serviceName: namesrv
  selector:
    matchLabels:
      app: rocketmq-namesrv
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-namesrv
    spec:
      containers:
      - image: reg.haimaiche.net/library/rocketmq-namesrv:4.7.0
        imagePullPolicy: Always
        name: rocketmq-namesrv
        ports:
        - protocol: TCP
          containerPort: 9876
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9876
          initialDelaySeconds: 120
          periodSeconds: 10
      imagePullSecrets:
        - name: reg-in