---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: NAMESPACE
  name: cm-rocketmq-console
data:
  JAVA_OPTS: "-Drocketmq.namesrv.addr=svc-rocketmq.NAMESPACE.svc.mhc.local:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"

---
kind: Service
apiVersion: v1
metadata:
  namespace: NAMESPACE
  name: svc-rocketmq-console
  labels:
    app: rocketmq-console
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: rocketmq-console
  type: ClusterIP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: NAMESPACE
  name: rocketmq-console
  labels:
    app: rocketmq-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-console
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-console
    spec:
      containers:
      - image: reg.haimaiche.net/ops/rocketmq-console:2.0.0
        securityContext:
          privileged: true
        imagePullPolicy: IfNotPresent
        name: rocketmq-console
        ports:
        - protocol: TCP
          containerPort: 8080
        envFrom:
        - configMapRef:
            name: cm-rocketmq-console
        resources:
          requests:
            cpu: 200m
            memory: 1.5Gi
          limits:
            cpu: 1
            memory: 1.5Gi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 15
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
      - name: reg-in